Sell
blockchain/bitcoin-coinify-client pull request #5
Opened 2017-03-27 14:01 UTC by prwelber

2017-03-27 14:13 UTC, jtormey commented
Could you fix the code style issues so that Travis passes?

2017-03-27 16:43 UTC, jtormey requested changes
Cool stuff @prwelber, made some minor comments.

It seems like the implementation details of bank account objects are being leaked. Might want to abstract that away. @Sjors what do you think?

2017-03-27 16:43 UTC, jtormey commented on bitcoin-coinify-client
> +bitcoin-coinify-client/node_modules/bitcoin-coinify-client
Is this necessary?

2017-03-27 16:43 UTC, jtormey commented on src/api.js
> +  DELETE (endpoint, data) {
Camel case please

2017-03-27 16:43 UTC, jtormey commented on src/bank.js
> +      return err;
This will swallow any error that happens here. Could you remove the `.catch` call? Or `throw err` if you want the console log to stay?

2017-03-27 16:43 UTC, jtormey commented on src/bank.js
> +    return;
Would rather this be an assertion or a promise rejection, returning `undefined` doesn't give the caller much to go off of.

2017-03-27 16:43 UTC, jtormey commented on src/bank.js
> +    return result;
This `.then` is unnecessary.

2017-03-27 16:43 UTC, jtormey commented on src/quote.js
> +          return res;
Not necessary.

2017-03-27 16:43 UTC, jtormey commented on src/trade.js
> +        this._lastFourBankAccountDigits = o.substring(o.length, o.length - 6);
Should this be the last four or last six digits?

2017-03-29 09:21 UTC, Sjors commented on bitcoin-coinify-client
> +bitcoin-coinify-client/node_modules/bitcoin-coinify-client
Sounds like you left an attempted symlink floating around.

2017-03-29 09:23 UTC, Sjors commented on src/api.js
> +  DELETE (endpoint, data) {
Actually I didn't use camel case for HTTP verbs in the other methods here either. We can change that later if needed.

2017-03-29 09:25 UTC, Sjors commented on src/bank.js
> +    return result;
`authGET()` already returns the result, so indeed the  `then((result) => { return result;` doesn't do anything.

2017-04-04 22:14 UTC, jtormey commented on src/trade.js
> +  sell (quote, bank) {
What's up with this method?

2017-04-05 07:14 UTC, prwelber commented on src/trade.js
> +  sell (quote, bank) {
tbh, not much. removing.

2017-04-05 09:01 UTC, merged